# Generated by Django 5.0.3 on 2024-04-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_catagory_price_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
