# Generated by Django 5.0.3 on 2024-04-26 08:08

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_remove_products_catagory_remove_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loversday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mothersday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Wedding',
        ),
    ]
