# Generated by Django 5.0.3 on 2024-05-07 06:13

import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_birthday_loversday_mothersday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posybouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Waterfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
