# Generated by Django 5.0.3 on 2024-05-20 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_cart_delete_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default = 1,on_delete=django.db.models.deletion.CASCADE, to='web_app.birthday'),
            preserve_default=False,
        ),
    ]
