# Generated by Django 5.0.3 on 2024-05-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default = 1,on_delete=django.db.models.deletion.CASCADE, to='web_app.wedding'),
        ),
    ]
