# Generated by Django 5.0.3 on 2024-05-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web_app', '0012_remove_cart_product_id_remove_cart_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='products',
            name='loversday',
        ),
        migrations.RemoveField(
            model_name='products',
            name='mothersday',
        ),
        migrations.RemoveField(
            model_name='products',
            name='posy',
        ),
        migrations.RemoveField(
            model_name='products',
            name='waterfall',
        ),
        migrations.RemoveField(
            model_name='products',
            name='wedding',
        ),
        migrations.AddField(
            model_name='products',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='products',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.products'),
        ),
    ]
