# Generated by Django 5.0.3 on 2024-05-25 10:18

import django.db.models.deletion
import django.utils.timezone
import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_remove_products_birthday_remove_products_loversday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName)),
                ('description', models.TextField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Loversday',
        ),
        migrations.DeleteModel(
            name='Mothersday',
        ),
        migrations.DeleteModel(
            name='Posybouquet',
        ),
        migrations.DeleteModel(
            name='Trending',
        ),
        migrations.DeleteModel(
            name='Waterfall',
        ),
        migrations.DeleteModel(
            name='Wedding',
        ),
        migrations.RemoveField(
            model_name='products',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='products',
            name='object_id',
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Default description', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Default name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=web_app.models.getFileName),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
        migrations.AddField(
            model_name='products',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default,1-trending'),
        ),
        migrations.AddField(
            model_name='products',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.catagory'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
