# Generated by Django 5.0.3 on 2024-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Gmail', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Pincode', models.IntegerField(default='')),
                ('City', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
