# Generated by Django 5.0.3 on 2024-06-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Gmail',
            new_name='Email',
        ),
    ]
